# Generated by Django 4.2.1 on 2024-05-08 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bakery', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cake',
            name='cake_image',
            field=models.ImageField(default='cake_images/default.jpg', upload_to='cake_images/'),
        ),
    ]
