# Generated by Django 4.2.1 on 2024-05-08 10:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bakery', '0002_cake_cake_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=100)),
                ('mobile_number', models.CharField(max_length=15)),
                ('payment_mode', models.CharField(choices=[('Cash', 'Cash'), ('PhonePe', 'PhonePe'), ('Google Pay', 'Google Pay'), ('Other', 'Other')], max_length=20)),
                ('total_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('cake', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bakery.cake')),
            ],
        ),
    ]
